
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/app/extra/clion/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.6.16-2-MANJARO - x86_64
...
